### PR TITLE
Import base64js library to support drag and drop MSG extension file

### PR DESCRIPTION
**Pull request by nguyenminhchien**

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
@nguyenminhchien Seems that CI is still red? could you check?

**Comment by nguyenminhchien** [comment]
@LoisRForgeFlow i added the dependency `cryptography<37`

**Comment by nguyenminhchien** [comment]
@LoisRForgeFlow pre-commit failed, please check
image

**Comment by LoisRForgeFlow** [comment]
@nguyenminhchien I have rebased the original PR and included your commit from this PR, let's continue the discussion there!

**Pull request closed without merging**
